pub mod agent_loop;
pub mod capture;
pub mod claude_detect;
pub mod command_parser;
pub mod config;
pub mod context;
pub mod error;
pub mod event_bus;
pub mod git_linker;
pub mod git_tracker;
pub mod profiles;
pub mod provider;
pub mod provider_registry;
pub mod scheduler;
pub mod scrubber;
pub mod session;
pub mod terminal_session;
pub mod tool_loop;
pub mod tool_registry;
pub mod types;

pub use agent_loop::AgentLoop;
pub use capture::HookBackend;
pub use claude_detect::ClaudeDetector;
pub use command_parser::CommandParser;
pub use config::AppConfig;
pub use context::ContextLinker;
pub use error::AgentError;
pub use event_bus::EventBus;
pub use git_linker::GitLinker;
pub use git_tracker::GitTracker;
pub use profiles::ProfileConfig;
pub use provider::ProviderChain;
pub use provider_registry::{ProviderInfo, ProviderKind, ProviderRegistry};
pub use scheduler::Scheduler;
pub use scrubber::SecretScrubber;
pub use session::{Session, SessionManager};
pub use terminal_session::TerminalSessionManager;
pub use tool_loop::{ToolLoopConfig, ToolLoopOutcome, ToolLoopStep};
pub use tool_registry::ToolRegistry;
